language: python
sudo: true
python:
  - "3.5"
# command to install dependencies
install: "./install.sh"
# command to run tests
before_script: source venv/bin/activate
script: python test/main.py 
branches:
  only:
    - master
    - dev
